# Generated by Django 6.0.2 on 2026-02-23 23:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('revision', 'En revisión'), ('archivada', 'Archivada')], default='activa', max_length=50)),
                ('costo_estimado_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('rol_profesional', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_rancho', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion_rancho', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('moneda', models.CharField(choices=[('MXN', 'Peso Mexicano'), ('USD', 'Dólar')], default='MXN', max_length=10)),
                ('unidad_peso', models.CharField(choices=[('kg', 'Kilogramo'), ('lb', 'Libra')], default='kg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad_actual_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoriainsumo')),
                ('proveedor_preferido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad_cabezas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_promedio_actual_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('etapa_productiva', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vendido', 'Vendido'), ('cuarentena', 'Cuarentena')], default='activo', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('dieta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dieta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='categoriainsumo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='AlimentacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_servida_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total_racion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dieta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dieta')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lote')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DietaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_inclusion', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)])),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dieta')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.insumo')),
            ],
            options={
                'unique_together': {('dieta', 'insumo')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=20)),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='api.insumo')),
            ],
            options={
                'indexes': [models.Index(fields=['insumo'], name='api_movimie_insumo__fd0746_idx'), models.Index(fields=['fecha_movimiento'], name='api_movimie_fecha_m_fd3b8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PesajeLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pesaje', models.DateField()),
                ('peso_promedio_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancia_diaria_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesajes', to='api.lote')),
            ],
            options={
                'indexes': [models.Index(fields=['lote'], name='api_pesajel_lote_id_227dea_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['usuario'], name='api_lote_usuario_e3dcd5_idx'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['usuario'], name='api_insumo_usuario_a64253_idx'),
        ),
        migrations.AddIndex(
            model_name='dieta',
            index=models.Index(fields=['usuario'], name='api_dieta_usuario_3f550e_idx'),
        ),
        migrations.AddIndex(
            model_name='alimentaciondiaria',
            index=models.Index(fields=['fecha'], name='api_aliment_fecha_6ac198_idx'),
        ),
    ]
