# Generated by Django 6.0.2 on 2026-04-05 20:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_auth_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_arete', models.CharField(max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('peso_nacimiento_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vendido', 'Vendido'), ('muerto', 'Muerto')], default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='api.lote')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crias_madre', to='api.animal')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crias_padre', to='api.animal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CicloReproductivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('natural', 'Monta Natural'), ('inseminacion_artificial', 'Inseminación Artificial')], max_length=30)),
                ('fecha_servicio', models.DateField()),
                ('dias_gestacion', models.IntegerField(default=283)),
                ('fecha_estimada_parto', models.DateField(blank=True, null=True)),
                ('fecha_parto_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_servicio', 'En Servicio'), ('gestante', 'Gestante'), ('pario', 'Parió'), ('fallida', 'Fallida'), ('descartada', 'Descartada')], default='en_servicio', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_reproductivos', to='api.animal')),
            ],
        ),
        migrations.CreateModel(
            name='EventoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacunacion', 'Vacunación'), ('desparasitacion', 'Desparasitación'), ('tratamiento', 'Tratamiento'), ('cirugia', 'Cirugía')], max_length=20)),
                ('producto', models.CharField(max_length=255)),
                ('dosis', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_aplicacion', models.DateField()),
                ('proxima_aplicacion', models.DateField(blank=True, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=255, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_sanitarios', to='api.animal')),
            ],
            options={
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pesaje', models.DateField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('condicion_corporal', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ganancia_diaria_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_peso', to='api.animal')),
            ],
            options={
                'ordering': ['-fecha_pesaje'],
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['usuario'], name='api_animal_usuario_359e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['lote'], name='api_animal_lote_id_5dbfae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together={('usuario', 'numero_arete')},
        ),
        migrations.AddIndex(
            model_name='cicloreproductivo',
            index=models.Index(fields=['animal'], name='api_ciclore_animal__d22bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='cicloreproductivo',
            index=models.Index(fields=['estado'], name='api_ciclore_estado_e67e81_idx'),
        ),
        migrations.AddIndex(
            model_name='eventosanitario',
            index=models.Index(fields=['animal'], name='api_eventos_animal__6ac6f2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventosanitario',
            index=models.Index(fields=['fecha_aplicacion'], name='api_eventos_fecha_a_fa7ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventosanitario',
            index=models.Index(fields=['proxima_aplicacion'], name='api_eventos_proxima_cf67e2_idx'),
        ),
        migrations.AddIndex(
            model_name='registropeso',
            index=models.Index(fields=['animal'], name='api_registr_animal__748277_idx'),
        ),
        migrations.AddIndex(
            model_name='registropeso',
            index=models.Index(fields=['fecha_pesaje'], name='api_registr_fecha_p_c1f4fa_idx'),
        ),
    ]
