# Generated by Django 5.1.4 on 2026-05-03 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_animal_cicloreproductivo_eventosanitario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido')], max_length=20)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_login', to='api.usuario')),
            ],
            options={
                'ordering': ['-fecha_intento'],
                'indexes': [models.Index(fields=['usuario'], name='api_auditor_usuario_a71914_idx'), models.Index(fields=['fecha_intento'], name='api_auditor_fecha_i_566330_idx'), models.Index(fields=['resultado'], name='api_auditor_resulta_fa2e8a_idx')],
            },
        ),
    ]
