# Generated by Django 5.1.4 on 2026-05-03 19:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auditoria_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='dias_lactancia',
            field=models.IntegerField(blank=True, help_text='Días actuales de lactation', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='fecha_ultimo_parto',
            field=models.DateField(blank=True, help_text='Fecha del último parto', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='partos_count',
            field=models.IntegerField(default=0, help_text='Número de partos registrados'),
        ),
        migrations.AddField(
            model_name='cicloreproductivo',
            name='fecha_destete',
            field=models.DateField(blank=True, help_text='Fecha estimada de destete', null=True),
        ),
        migrations.AddField(
            model_name='cicloreproductivo',
            name='formato',
            field=models.CharField(choices=[('temporada', 'Temporada'), ('continuo', 'Continuo')], default='continuo', help_text='Cómo se maneja: por temporada o continuo', max_length=20),
        ),
        migrations.AddField(
            model_name='cicloreproductivo',
            name='temporada',
            field=models.CharField(blank=True, help_text='Nombre de temporada ej: "Primavera 2026"', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dieta',
            name='cantidad_kg_cabeza',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kg por cabeza por período', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dieta',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dieta',
            name='periodicidad',
            field=models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal')], default='diaria', max_length=20),
        ),
        migrations.AddField(
            model_name='dieta',
            name='tipo_formulacion',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje'), ('tabla_kg', 'Tabla kg')], default='porcentaje', max_length=20),
        ),
        migrations.AddField(
            model_name='dietainsumo',
            name='cantidad_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad en kg por cabeza (formato tabla_kg)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='dietainsumo',
            name='porcentaje_inclusion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de inclusión (formato porcentaje)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='RegistroNacimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_arete', models.CharField(blank=True, help_text='Número de arete de la cria', max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('peso_nacimiento_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_destete', models.DateField(blank=True, help_text='Fecha de destete', null=True)),
                ('anomalies', models.TextField(blank=True, help_text='Anomalías o complicaciones al nacimiento', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nacimientos', to='api.cicloreproductivo')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nacimientos', to='api.animal')),
            ],
            options={
                'indexes': [models.Index(fields=['madre'], name='api_registr_madre_i_c28bca_idx'), models.Index(fields=['fecha_nacimiento'], name='api_registr_fecha_n_f3eabb_idx')],
            },
        ),
    ]
