# Generated by Django 5.1.4 on 2026-05-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alimentacion_reproduccion_fase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('basico', 'Básico'), ('productor', 'Productor'), ('empresarial', 'Empresarial')], max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_animales', models.IntegerField(default=50)),
                ('limite_usuarios', models.IntegerField(default=1)),
                ('incluye_modulo_animales', models.BooleanField(default=True)),
                ('incluye_modulo_lotes', models.BooleanField(default=True)),
                ('incluye_modulo_dietas', models.BooleanField(default=True)),
                ('incluye_modulo_sanitaria', models.BooleanField(default=True)),
                ('incluye_reportes_avanzados', models.BooleanField(default=False)),
                ('incluye_api', models.BooleanField(default=False)),
                ('soporte_prioritario', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['precio_mxn'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='SuscripcionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_renovacion', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_cancelacion', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscriptores', to='api.plansuscripcion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Solo lectura')], default='editor', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True)),
                ('cuenta_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='api.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_acceso', to='api.usuario')),
            ],
            options={
                'unique_together': {('cuenta_principal', 'usuario')},
            },
        ),
    ]
