# Generated by Django 5.1.4 on 2026-05-11 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_plansuscripcion_alter_usuario_nombre_completo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tipo_produccion', models.CharField(blank=True, help_text='Ej: ganadería, agricultura', max_length=100, null=True)),
                ('tamaño_hectareas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario_propietario', models.ForeignKey(help_text='Usuario propietario/creador de la farm', on_delete=django.db.models.deletion.CASCADE, related_name='farms_propias', to='api.usuario')),
                ('usuarios', models.ManyToManyField(help_text='Usuarios que pueden acceder a esta farm', related_name='farms_acceso', to='api.usuario')),
            ],
            options={
                'indexes': [models.Index(fields=['usuario_propietario'], name='api_farm_usuario_f71380_idx'), models.Index(fields=['activa'], name='api_farm_activa_55a8dd_idx')],
            },
        ),
    ]
