# Generated by Django 5.1.4 on 2026-05-09

from django.db import migrations


def crear_planes(apps, schema_editor):
    PlanSuscripcion = apps.get_model('api', 'PlanSuscripcion')

    planes_data = [
        {
            'codigo': 'basico',
            'nombre': 'Básico',
            'descripcion': 'Para pequeños productores con pocas cabezas',
            'precio_mxn': 0,
            'precio_anual': 0,
            'limite_animales': 20,
            'limite_usuarios': 1,
            'incluye_modulo_animales': True,
            'incluye_modulo_lotes': False,
            'incluye_modulo_dietas': False,
            'incluye_modulo_sanitaria': True,
            'incluye_reportes_avanzados': False,
            'incluye_api': False,
            'soporte_prioritario': False,
        },
        {
            'codigo': 'profesional',
            'nombre': 'Profesional',
            'descripcion': 'Para productores medianos',
            'precio_mxn': 149,
            'precio_anual': 1611,
            'limite_animales': 100,
            'limite_usuarios': 3,
            'incluye_modulo_animales': True,
            'incluye_modulo_lotes': True,
            'incluye_modulo_dietas': True,
            'incluye_modulo_sanitaria': True,
            'incluye_reportes_avanzados': True,
            'incluye_api': False,
            'soporte_prioritario': False,
        },
        {
            'codigo': 'productor',
            'nombre': 'Productor',
            'descripcion': 'Para ranchos medianos y grandes',
            'precio_mxn': 299,
            'precio_anual': 3231,
            'limite_animales': 300,
            'limite_usuarios': 5,
            'incluye_modulo_animales': True,
            'incluye_modulo_lotes': True,
            'incluye_modulo_dietas': True,
            'incluye_modulo_sanitaria': True,
            'incluye_reportes_avanzados': True,
            'incluye_api': True,
            'soporte_prioritario': True,
        },
        {
            'codigo': 'empresarial',
            'nombre': 'Empresarial',
            'descripcion': 'Para empresas ganaderas con múltiples ranchos',
            'precio_mxn': 599,
            'precio_anual': 6471,
            'limite_animales': 999999,
            'limite_usuarios': 999999,
            'incluye_modulo_animales': True,
            'incluye_modulo_lotes': True,
            'incluye_modulo_dietas': True,
            'incluye_modulo_sanitaria': True,
            'incluye_reportes_avanzados': True,
            'incluye_api': True,
            'soporte_prioritario': True,
        },
    ]

    for plan_data in planes_data:
        PlanSuscripcion.objects.update_or_create(
            codigo=plan_data['codigo'],
            defaults=plan_data
        )


def reverse_func(apps, schema_editor):
    PlanSuscripcion = apps.get_model('api', 'PlanSuscripcion')
    PlanSuscripcion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_plansuscripcion_alter_usuario_nombre_completo_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_planes, reverse_func),
    ]
