# Generated by Django 5.1.2 on 2026-03-22 (o la fecha de creación de tu proyecto)
from django.db import migrations

def crear_planes(apps, schema_editor):
    PlanSuscripcion = apps.get_model('api', 'PlanSuscripcion')
    
    # Datos de los planes definidos originalmente en tu migración
    planes = [
        {
            'codigo': 'basico',
            'nombre': 'Básico',
            'descripcion': 'Plan gratuito para pequeños productores y control inicial.',
            'precio_mxn': 0.00,
            'precio_anual': 0.00,
            'limite_animales': 50,
            'limite_usuarios': 1,
            'incluye_modulo_animales': True,
            'incluye_modulo_lotes': True,
            'incluye_modulo_dietas': True,
            'incluye_modulo_sanitaria': True,
            'incluye_reportes_avanzados': False,
            'incluye_api': False,
            'soporte_prioritario': False,
            'activo': True
        },
        {
            'codigo': 'productor',
            'nombre': 'Productor',
            'descripcion': 'Para ranchos en crecimiento con requerimientos de reportes y múltiples usuarios.',
            'precio_mxn': 349.00,
            'precio_anual': 3490.00,
            'limite_animales': 500,
            'limite_usuarios': 5,
            'incluye_modulo_animales': True,
            'incluye_modulo_lotes': True,
            'incluye_modulo_dietas': True,
            'incluye_modulo_sanitaria': True,
            'incluye_reportes_avanzados': True,
            'incluye_api': False,
            'soporte_prioritario': False,
            'activo': True
        },
        {
            'codigo': 'empresarial',
            'nombre': 'Empresarial',
            'descripcion': 'Acceso ilimitado, integración con API y soporte prioritario 24/7.',
            'precio_mxn': 899.00,
            'precio_anual': 8990.00,
            'limite_animales': 99999,
            'limite_usuarios': 20,
            'incluye_modulo_animales': True,
            'incluye_modulo_lotes': True,
            'incluye_modulo_dietas': True,
            'incluye_modulo_sanitaria': True,
            'incluye_reportes_avanzados': True,
            'incluye_api': True,
            'soporte_prioritario': True,
            'activo': True
        }
    ]

    for plan_data in planes:
        codigo = plan_data.pop('codigo')
        
        # Obtenemos o creamos el registro base utilizando el código único
        plan_obj, created = PlanSuscripcion.objects.get_or_create(codigo=codigo)
        
        # Recorremos cada propiedad e inyectamos el valor únicamente si el modelo
        # tiene ese campo creado en el punto actual del historial.
        for key, value in plan_data.items():
            if hasattr(plan_obj, key):
                setattr(plan_obj, key, value)
                
        plan_obj.save()

def eliminar_planes(apps, schema_editor):
    PlanSuscripcion = apps.get_model('api', 'PlanSuscripcion')
    PlanSuscripcion.objects.filter(codigo__in=['basico', 'productor', 'empresarial']).delete()

class Migration(migrations.Migration):

    dependencies = [
        # Se mantiene la dependencia original sin bucles circulares
        ('api', '0006_plansuscripcion_alter_usuario_nombre_completo_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_planes, reverse_code=eliminar_planes),
    ]