# Generated by Django 5.1.4 on 2026-05-11 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm a la que pertenece este animal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='api.farm'),
        ),
        migrations.AddField(
            model_name='categoriainsumo',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm a la que pertenece esta categoría', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_insumo', to='api.farm'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm a la que pertenece esta dieta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietas', to='api.farm'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm a la que pertenece este insumo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='api.farm'),
        ),
        migrations.AddField(
            model_name='lote',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm a la que pertenece este lote', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='api.farm'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm a la que pertenece este proveedor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='api.farm'),
        ),
    ]
