# Generated by Django 5.1.4 on 2026-05-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_actualizar_precios_planes'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fecha_ultimo_peso',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='ultimo_peso_kg',
            field=models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='total_eventos_sanitarios',
            field=models.IntegerField(default=0),
        ),
    ]
