# Generated by Django 5.1.4 on 2026-05-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_animal_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuscripcion',
            name='precio_anual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
