# Generated by Django 5.1.4 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_plansuscripcion_precio_anual'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fecha_ultimo_peso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='total_eventos_sanitarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='ultimo_peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
