# Generated by Django 5.1.4 on 2026-05-17 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_animal_campos_registros'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoría', to='api.animal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoría', to='api.usuario')),
            ],
            options={
                'ordering': ['fecha_cambio'],
                'indexes': [models.Index(fields=['animal'], name='api_auditor_animal__ab1169_idx'), models.Index(fields=['fecha_cambio'], name='api_auditor_fecha_c_438e24_idx')],
            },
        ),
    ]
