# Generated by Django 6.0.5 on 2026-05-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_auditoriaanimal_usuario'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS api_plansuscripcion (id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, codigo VARCHAR(20) NOT NULL UNIQUE, nombre VARCHAR(100) NOT NULL, descripcion TEXT, precio_mxn NUMERIC(10,2) NOT NULL DEFAULT 0, precio_anual NUMERIC(10,2) NOT NULL DEFAULT 0, limite_animales INTEGER NOT NULL DEFAULT 50, limite_usuarios INTEGER NOT NULL DEFAULT 1, incluye_modulo_animales BOOLEAN NOT NULL DEFAULT TRUE, incluye_modulo_lotes BOOLEAN NOT NULL DEFAULT TRUE, incluye_modulo_dietas BOOLEAN NOT NULL DEFAULT TRUE, incluye_modulo_sanitaria BOOLEAN NOT NULL DEFAULT TRUE, incluye_reportes_avanzados BOOLEAN NOT NULL DEFAULT FALSE, incluye_api BOOLEAN NOT NULL DEFAULT FALSE, soporte_prioritario BOOLEAN NOT NULL DEFAULT FALSE, activo BOOLEAN NOT NULL DEFAULT TRUE)",
            "DROP TABLE IF EXISTS api_plansuscripcion"
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS api_suscripcionusuario (id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, usuario_id BIGINT NOT NULL REFERENCES api_usuario(id) UNIQUE, plan_id BIGINT NOT NULL REFERENCES api_plansuscripcion(id), fecha_inicio DATE NOT NULL DEFAULT CURRENT_DATE, fecha_renovacion DATE, activa BOOLEAN NOT NULL DEFAULT TRUE, fecha_cancelacion DATE)",
            "DROP TABLE IF EXISTS api_suscripcionusuario"
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS api_usuarioinvitado (id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, cuenta_principal_id BIGINT NOT NULL REFERENCES api_usuario(id), usuario_id BIGINT NOT NULL REFERENCES api_usuario(id), rol VARCHAR(20) NOT NULL DEFAULT 'editor', activo BOOLEAN NOT NULL DEFAULT TRUE, fecha_invitacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), CONSTRAINT api_usuarioinvitado_unique UNIQUE (cuenta_principal_id, usuario_id))",
            "DROP TABLE IF EXISTS api_usuarioinvitado"
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS api_registronacimiento (id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, ciclo_id BIGINT NOT NULL REFERENCES api_cicloreproductivo(id), madre_id BIGINT NOT NULL REFERENCES api_animal(id), numero_arete VARCHAR(100), nombre VARCHAR(100), sexo VARCHAR(1) NOT NULL, peso_nacimiento_kg NUMERIC(8,2), fecha_nacimiento DATE, fecha_destete DATE, anomalies TEXT, observaciones TEXT, fecha_registro TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW())",
            "DROP TABLE IF EXISTS api_registronacimiento"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS api_registronacimiento_madre_id ON api_registronacimiento(madre_id); CREATE INDEX IF NOT EXISTS api_registronacimiento_fecha_nacimiento ON api_registronacimiento(fecha_nacimiento)",
            "DROP INDEX IF EXISTS api_registronacimiento_madre_id; DROP INDEX IF EXISTS api_registronacimiento_fecha_nacimiento"
        ),
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS api_auditorialogin (id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, usuario_id BIGINT REFERENCES api_usuario(id), email VARCHAR(254) NOT NULL, ip_address INET, user_agent VARCHAR(500), resultado VARCHAR(20) NOT NULL, mensaje TEXT, fecha_intento TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW())",
            "DROP TABLE IF EXISTS api_auditorialogin"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS api_auditorialogin_usuario_id ON api_auditorialogin(usuario_id); CREATE INDEX IF NOT EXISTS api_auditorialogin_fecha_intento ON api_auditorialogin(fecha_intento); CREATE INDEX IF NOT EXISTS api_auditorialogin_resultado ON api_auditorialogin(resultado)",
            "DROP INDEX IF EXISTS api_auditorialogin_usuario_id; DROP INDEX IF EXISTS api_auditorialogin_fecha_intento; DROP INDEX IF EXISTS api_auditorialogin_resultado"
        ),
    ]
