# Generated by Django 5.1.4 on 2026-05-26 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_auditoriaanimal_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('vendido', 'Vendido'), ('muerto', 'Muerto'), ('transferido', 'Transferido')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoriaanimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='api.animal'),
        ),
    ]
