# Generated by Django 6.0.5 on 2026-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_fix_missing_tables_and_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='dias_lactancia',
            field=models.IntegerField(blank=True, help_text='Días actuales de lactation', null=True),
        ),
    ]
