# Generated by Django 6.0.5 on 2026-05-25 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_animal_dias_lactancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaanimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='api.animal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(max_length=255),
        ),
    ]
