# Generated by Django 5.1.4 on 2026-05-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_animal_estado_alter_auditoriaanimal_animal'),
        ('api', '0016_alter_auditoriaanimal_animal_and_more'),
    ]

    operations = [
    ]
