# Generated by Django 5.1.4 on 2026-07-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20260526_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='peso_nacimiento_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raza',
            field=models.CharField(max_length=100),
        ),
    ]
