# Generated by Django 5.1.4 on 2026-09-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_animal_fecha_nacimiento_and_more'),
        ('api', '0019_usuario_ubicacion_rancho'),
    ]

    operations = [
    ]
