# Generated by Django 5.1.4 on 2026-09-17 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20260916_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventos_sanitarios', models.BooleanField(default=True)),
                ('partos_proximos', models.BooleanField(default=True)),
                ('stock_bajo', models.BooleanField(default=True)),
                ('dias_anticipacion_sanitario', models.IntegerField(default=7)),
                ('dias_anticipacion_parto', models.IntegerField(default=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_notificaciones', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('evento_sanitario', 'Evento Sanitario Próximo'), ('parto_proximo', 'Parto Próximo'), ('stock_bajo', 'Stock Bajo')], max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('enviada_push', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='api.usuario')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='api_notific_usuario_532dfb_idx'), models.Index(fields=['fecha_creacion'], name='api_notific_fecha_c_bd7a58_idx')],
            },
        ),
    ]
