# Generated by Django 5.1.4 on 2026-09-19 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_animal_fecha_nacimiento_and_more'),
        ('api', '0020_animal_foto'),
    ]

    operations = [
    ]
