# Generated by Django 5.1.4 on 2026-09-20 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20260919_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentaciondiaria',
            name='notas',
            field=models.TextField(blank=True, help_text='Marcador interno (ej. animal_id:12 para dietas especiales)', null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='dieta',
            field=models.ForeignKey(blank=True, help_text='Dieta especial individual (enfermo, condición o trato distinto)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales_asignados', to='api.dieta'),
        ),
        migrations.AlterField(
            model_name='alimentaciondiaria',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lote'),
        ),
    ]
