# Generated by Django 5.1.4 on 2026-09-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_preferencianotificacion_notificacion'),
        ('api', '0022_consumo_dietas'),
    ]

    operations = [
    ]
