# Generated by Django 5.1.4 on 2026-09-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20260923_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='estado',
            field=models.CharField(
                choices=[
                    ('activa', 'Activa'),
                    ('inactiva', 'Inactiva'),
                    ('revision', 'En revisión'),
                    ('archivada', 'Archivada'),
                ],
                default='activa',
                max_length=50,
            ),
        ),
    ]
