"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Cargar variables de entorno
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Crear carpeta de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r0ps7o_+9un$-h)%42r#mve)xs(-xzwjj*t4&w%ia-&zf(p(#k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Aceptar desde cualquier IP (desarrollo)

# Define la URL del backend para envio de correos de verificación y otros propósitos
BACKEND_URL = os.getenv(
    "BACKEND_URL",
    "http://localhost:8000"
)

# Identificación requerida por OpenStreetMap/Nominatim. Debe apuntar a un
# contacto operativo en producción.
BOVION_EXTERNAL_USER_AGENT = os.getenv(
    'BOVION_EXTERNAL_USER_AGENT',
    'Bovion/1.0 (contacto@bovion.com)',
)
WEATHER_HTTP_TIMEOUT_SECONDS = float(os.getenv('WEATHER_HTTP_TIMEOUT_SECONDS', '8'))

CACHES = {
    'default': {
        'BACKEND': os.getenv(
            'DJANGO_CACHE_BACKEND',
            'django.core.cache.backends.locmem.LocMemCache',
        ),
        'LOCATION': os.getenv('DJANGO_CACHE_LOCATION', 'bovion-cache'),
    }
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',  # Para documentación de la API automatizada
    'anymail',
    'api',  # Tu app de API
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe ir al principio
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),  # Carpeta para el template de React
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database - Supabase PostgreSQL
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres.vcxdtkekiweomnemfwdk'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        # CAMBIAR el host al Transaction Pooler (puerto 6543)
        'HOST': os.getenv('DB_HOST', 'aws-1-us-east-2.pooler.supabase.com'),
        'PORT': os.getenv('DB_PORT', '6543'),  # <-- cambiar 5432 por 6543
        'CONN_MAX_AGE': 0,  # <-- cambiar 600 por 0
        'OPTIONS': {} if os.getenv('DB_HOST', 'aws-1-us-east-2.pooler.supabase.com') in ('localhost', '127.0.0.1', 'db', 'host.docker.internal') else {
            'sslmode': 'require',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'  # Cambiado a español

TIME_ZONE = 'America/Bogota'  # Ajusta según tu zona horaria

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Donde Vite construirá los archivos
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (para archivos subidos por usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Puerto de desarrollo de Vite
    "http://127.0.0.1:5173",
    "http://10.0.2.2:8000",  # Android emulator
]

# Si quieres permitir todas las credenciales (cookies, headers de autorización)
CORS_ALLOW_CREDENTIALS = True

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# JWT configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,
}

# Email configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 'yes')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@bovion.com')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# Optional AnyMail (SendGrid/Mailgun) configuration for easier, secure delivery
# Set USE_ANYMAIL=True and the provider-specific API key in environment variables.
USE_ANYMAIL = os.getenv('USE_ANYMAIL', 'False').lower() in ('true', '1', 'yes')
if USE_ANYMAIL:
    # Prefer AnyMail backends (API-based) for reliability and metrics
    # Example: AnyMail + SendGrid
    EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'anymail.backends.sendgrid.EmailBackend')
    ANYMAIL = {
        'SENDGRID_API_KEY': os.getenv('SENDGRID_API_KEY', ''),
        # 'MAILGUN_API_KEY': os.getenv('MAILGUN_API_KEY', ''),
        # Add other provider keys as needed
    }
else:
    # Allow traditional SMTP backend via env vars (configured above)
    EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', EMAIL_BACKEND)

# Basic validation: in production require sensible email settings
if not DEBUG:
    missing = []
    if EMAIL_BACKEND and 'smtp' in EMAIL_BACKEND and not EMAIL_HOST:
        missing.append('EMAIL_HOST')
    if EMAIL_BACKEND and 'smtp' in EMAIL_BACKEND and not EMAIL_HOST_USER:
        missing.append('EMAIL_HOST_USER')
    if EMAIL_BACKEND and 'smtp' in EMAIL_BACKEND and not EMAIL_HOST_PASSWORD:
        missing.append('EMAIL_HOST_PASSWORD')
    if USE_ANYMAIL and not any(ANYMAIL.values()):
        missing.append('ANYMAIL provider API key (e.g. SENDGRID_API_KEY)')
    if missing:
        raise ImproperlyConfigured('Missing required email configuration for production: ' + ', '.join(missing))

# Logging
import logging.handlers

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'agrogestor.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 30,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
